name: datanalytics_env
channels:
  - conda-forge
  - https://repo.anaconda.com/pkgs/main
  - https://repo.anaconda.com/pkgs/r
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - asgiref=3.8.1
  - bzip2=1.0.8
  - ca-certificates=2024.12.14
  - django=5.1.4
  - ld_impl_linux-64=2.43
  - libblas=3.9.0
  - libcblas=3.9.0
  - libexpat=2.6.4
  - libffi=3.4.2
  - libgcc=14.2.0
  - libgcc-ng=14.2.0
  - libgfortran=14.2.0
  - libgfortran5=14.2.0
  - libgomp=14.2.0
  - liblapack=3.9.0
  - liblzma=5.6.3
  - libnsl=2.0.1
  - libopenblas=0.3.28
  - libsqlite=3.47.2
  - libstdcxx=14.2.0
  - libuuid=2.38.1
  - libxcrypt=4.4.36
  - libzlib=1.3.1
  - ncurses=6.5
  - numpy=2.2.1
  - openssl=3.4.0
  - pandas=2.2.3
  - pip=24.3.1
  - python=3.12.8
  - python-dateutil=2.9.0.post0
  - python-tzdata=2024.2
  - python_abi=3.12
  - pytz=2024.1
  - readline=8.2
  - setuptools=75.6.0
  - six=1.17.0
  - sqlparse=0.5.3
  - tk=8.6.13
  - typing_extensions=4.12.2
  - tzdata=2024b
  - wheel=0.45.1
  - pip:
      - confusable-homoglyphs==3.3.1
      - django-registration==5.1.0
      - django-widget-tweaks==1.5.0
      - python-dotenv==1.0.1
