name: datanalytics_env
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.11.5
  - pip=23.3.1
  - django=5.1.3
  - postgresql=15.4
  - redis-py=5.0.1
  - celery=5.3.4
  - pandas=1.5.3
  - numpy=1.24.3
  - matplotlib=3.7.2
  - scipy=1.11.4
  - setuptools=68.2.2
  - wheel=0.41.2
  - pip:
    - psycopg2-binary==2.9.10
    - django-registration==3.4
    - django-widget-tweaks==1.5.0
    - python-dotenv==1.0.1
    - sweetviz==2.1.3
    - redis==5.0.1
