# Generated by Django 5.1.4 on 2025-01-20 12:58

import django.core.validators
import django.db.models.deletion
import projects.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('input_dataframe', models.FileField(upload_to=projects.models.get_input_dataframe_file_name, validators=[django.core.validators.FileExtensionValidator(['csv'])])),
                ('param_file', models.FileField(upload_to=projects.models.get_param_file_name, validators=[django.core.validators.FileExtensionValidator(['json'])])),
                ('sweetviz_report', models.FileField(blank=True, null=True, upload_to='reports/')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('name', 'user'), name='unique_project')],
            },
        ),
    ]
