# Generated by Django 5.1.4 on 2025-02-01 12:02

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_project_prep_output_project_train_eval_output'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='description',
            field=models.TextField(default=django.utils.timezone.now, help_text='Provide a detailed description of your project'),
            preserve_default=False,
        ),
    ]
