# Generated by Django 5.1.2 on 2024-12-20 10:33

import django.core.validators
import projects.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_project_unique_project'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='input_dataframe',
            field=models.FileField(upload_to=projects.models.get_input_dataframe_file_name, validators=[django.core.validators.FileExtensionValidator(['csv'])]),
        ),
        migrations.AlterField(
            model_name='project',
            name='param_file',
            field=models.FileField(default=projects.models.get_param_file_name, upload_to=projects.models.get_param_file_name),
        ),
    ]
