# Generated by Django 5.1.4 on 2025-01-15 15:37

import django.core.validators
import projects.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_alter_project_input_dataframe_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='sweetviz_report',
            field=models.FileField(blank=True, null=True, upload_to='reports/'),
        ),
        migrations.AlterField(
            model_name='project',
            name='param_file',
            field=models.FileField(upload_to=projects.models.get_param_file_name, validators=[django.core.validators.FileExtensionValidator(['json'])]),
        ),
    ]
